# echo 'root' | docker secret create DB_ROOT_PASSWORD -
# echo 'xtra' | docker secret create XTRABACKUP_PASSWORD -
#
# docker network create -d overlay --attachable dbcluster
#
# docker stack deploy -c swarm.stack.yml dbcluster
version: "3.8"

services:
    adminer:
        image: adminer
        deploy:
            replicas: 1
        ports:
            - "8080:8080"
        networks:
            - internal_dbcluster
        environment:
            - ADMINER_DEFAULT_SERVER=db
            - ADMINER_PLUGINS=tables-filter dump-bz2 dump-date

    db:
        image: pitilezard/mariadb-galera-swarm:10.3@sha256:e5270a21efade6c7961b4b54a3da1dc7a109da86bfe7eeabcffa088ebd00e281
        secrets:
            - XTRABACKUP_PASSWORD
            - DB_ROOT_PASSWORD
        deploy:
            mode: global
            update_config:
                parallelism: 1
            placement:
                constraints:
                    - "node.labels.db_node==1"
        networks:
            - internal_dbcluster
            - dbcluster

        # start one node with the seed command by tagging that node with db_node=1
        # then when that node finished seeding that database, switch the command to "node db"
        # minimum of 2 nodes is required for all of them to sync up
        command: seed
        # command: node db

        volumes:
            - mysql-data:/var/lib/mysql:rw
        environment:
            - XTRABACKUP_PASSWORD_FILE=/run/secrets/XTRABACKUP_PASSWORD
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/DB_ROOT_PASSWORD
            - HEALTHY_WHILE_BOOTING=1
            - MYSQL_ROOT_HOST=%

volumes:
    mysql-data:
        name: "{{.Service.Name}}-data"
        driver: local

networks:
    internal_dbcluster:
        driver: overlay
    dbcluster:
        name: intra
        external: true

secrets:
    DB_ROOT_PASSWORD:
        external: true
    XTRABACKUP_PASSWORD:
        external: true
